// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	endpoint "ledger/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeRegisterHandler(m, endpoints, options["Register"])
	makeAuthenticateHandler(m, endpoints, options["Authenticate"])
	makeNewAccountHandler(m, endpoints, options["NewAccount"])
	makeGetAccountsHandler(m, endpoints, options["GetAccounts"])
	makeNewTransactionHandler(m, endpoints, options["NewTransaction"])
	makeGetBalanceHandler(m, endpoints, options["GetBalance"])
	makeGetTransactionsHandler(m, endpoints, options["GetTransactions"])
	return m
}
